# Generated by Django 4.1.5 on 2023-01-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_pub_data_note_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
